#+TITLE: Matrix.el - Emacs-Lisp interface to the Matrix Distributed Chat

* Installation

Right now this is just a single directoy that you put in to your =load-path= and require with
=(require 'mclient)=. Eventually I'll put it in MELPA or something so that you can install it via
=package.el=.

* Usage

There are two parts, a low-level API, and a terrible barely-alpha-quality client.

** matrix.el

This is a low-level API right now; I'm planning to wrap it with high-level API that lets you easily
per-room events, and that sort of thing, and eventually a full-fledged Matrix client. The API itself
is pretty tightly based on the official Python API.

#+BEGIN_SRC emacs-lisp
(let ((matrix-homeserver-base-url "https://yourhs.org"))
  (unless matrix-token
    (matrix-login-with-password "@you:yourhs.org" "[REDACTED]"))
  (matrix-initial-sync 1)
  (matrix-send-message "!yourroom:matrix.org" "Test post please ignore"))
#+END_SRC

** mclient.el

This is a pretty rough implementation of a Matrix client; hopefully it'll become less rough as I
work on it. =M-x mclient= will prompt you for a username and password, and jack you in to the
matrix.org homeserver, unless you override =matrix-homeserver-base-url= to provide your own.

It barely works, and does a lot of janky things, but it is passable as a client for now. It may not
handle network reconnects and such things well right now, feel free to =M-x mclient-reconnect= if
you think it's misbehaving.

* Contributing


To submit patches:
- Clone the repo
- Create a git branch, code in a branch.
- When you're done, send me a =git format-patch= style patch
  - =git format-patch --to ryan@whatthefuck.computer master..HEAD > YOURBRANCHNAME.patch=
  - Mail that patch to me at [[mailto:ryan@whatthefuck.computer][ryan@whatthefuck.computer]], and I will integrate it.
    - Or send it to me on Matrix, I'm =@rrix:whatthefuck.computer=

Project Discussion happens in =#ft_kickass:whatthefuck.computer=

* License

See LICENSE in the root of the repository for legal information.
