#+TITLE: [LEGACY] Matrix.el

* Preface

This is a fork of the [[https://home.rix.si/git/rrix/matrix-client][original matrix.el client]], to attempt to resurrect
it. It's probably not going to succeed though.

Most of the additions I'm going to be adding are going to be for myself only, so
they'll probably break other people's usage of it.

Ideally, I'll make a *new* matrix.el on the python sdk, but that will have to
wait for another day.

Below is the original README. Hopefully this helps someone, but it's unlikely.

* Installation

=matrix-client= is installable via MELPA. Otherwise you can add this directory to your =load-path=
and =(require 'matrix-client)=.

* Usage

There are two parts, a low-level API, and a terrible barely-alpha-quality client.

Either deploy your own homeserver or register account on the public homeserver
https://matrix.org/beta/#/login . After you've done that, =M-x matrix-client= will set you up with
buffers corresponding to your Matrix rooms. You can join new ones with /join, leave with /leave or
/part, and hook in to the custom functions provided by =matrix-client=.

=matrix-api= is a low-level API right now; I'm planning to wrap it with high-level API that lets you easily
per-room events, and that sort of thing, and eventually a full-fledged Matrix client. The API itself
is pretty tightly based on the official Python API.

#+BEGIN_SRC emacs-lisp
(let ((matrix-homeserver-base-url "https://yourhs.org"))
  (unless matrix-token
    (matrix-login-with-password "@you:yourhs.org" "[REDACTED]"))
  (matrix-initial-sync 1)
  (matrix-send-message "!yourroom:matrix.org" "Test post please ignore"))
#+END_SRC

* Contributing


To submit patches:
- Clone the repo
- Create a git branch, code in a branch.
- When you're done, send me a =git format-patch= style patch
  - =git format-patch --to ryan@whatthefuck.computer master..HEAD > YOURBRANCHNAME.patch=
  - Mail that patch to me at [[mailto:ryan@whatthefuck.computer][ryan@whatthefuck.computer]], and I will integrate it.
    - Or send it to me on Matrix, I'm =@rrix:whatthefuck.computer=

Project Discussion happens in =#ft_kickass:whatthefuck.computer=

* License

See LICENSE in the root of the repository for legal information.
